/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package transversal_vista;

import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import transversal_accesoDeDatos.AlumnoData;
import transversal_entidades.Alumno;


public class FormularioAlumnoJIF extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioAlumnoJIF
     */
    private AlumnoData aluData = new AlumnoData();
    private Alumno alumnoActual = null;
    
    public FormularioAlumnoJIF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_AlumnoTItulo = new javax.swing.JLabel();
        jButton_buscar = new javax.swing.JButton();
        jTextField_dni = new javax.swing.JTextField();
        jLabel_dni = new javax.swing.JLabel();
        jLabel_apellido = new javax.swing.JLabel();
        jTextField_apellido = new javax.swing.JTextField();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_Estado = new javax.swing.JLabel();
        jCheckBox_Activo = new javax.swing.JCheckBox();
        jDateChooser_fechaNaci = new com.toedter.calendar.JDateChooser();
        jLabel_fechaNac = new javax.swing.JLabel();
        jButton_nuevo2 = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Alumno");

        jLabel_AlumnoTItulo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel_AlumnoTItulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/students.png"))); // NOI18N
        jLabel_AlumnoTItulo.setText(" Alumno");

        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/buscar.png"))); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel_dni.setText("DNI:");

        jLabel_apellido.setText("Apellido:");

        jTextField_apellido.setText(" ");
        jTextField_apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellidoActionPerformed(evt);
            }
        });

        jTextField_nombre.setText(" ");
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jLabel_nombre.setText("Nombre:");

        jLabel_Estado.setText("Activo:");

        jCheckBox_Activo.setSelected(true);

        jLabel_fechaNac.setText("Fecha de nacimiento:");

        jButton_nuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/mas.png"))); // NOI18N
        jButton_nuevo2.setText("Nuevo");
        jButton_nuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo2ActionPerformed(evt);
            }
        });

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/borrar.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/guardar-el-archivo.png"))); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/salir.png"))); // NOI18N
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_salir)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_nombre)
                                .addComponent(jLabel_Estado))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jCheckBox_Activo)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField_nombre)
                                    .addGap(109, 109, 109))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_apellido)
                                .addComponent(jLabel_dni))
                            .addGap(51, 51, 51)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                                    .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel_AlumnoTItulo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_fechaNac)
                            .addGap(18, 18, 18)
                            .addComponent(jDateChooser_fechaNaci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel_AlumnoTItulo)
                    .addGap(27, 27, 27)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_dni)
                        .addComponent(jButton_buscar))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_apellido)
                        .addComponent(jTextField_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_nombre)
                        .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Estado)
                        .addComponent(jCheckBox_Activo))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel_fechaNac)
                        .addComponent(jDateChooser_fechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(132, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        try {
            Integer dni = Integer.parseInt(jTextField_dni.getText());
            String nombre = jTextField_nombre.getText();
            String apellido = jTextField_apellido.getText();
            if ( !nombre.isEmpty() && !apellido.isEmpty() ) {
                //extracción de datos
                java.util.Date fechaNacDate = jDateChooser_fechaNaci.getDate();
                //de Date a localdate
                LocalDate fechaNacLocalDate = fechaNacDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                boolean estado = jCheckBox_Activo.isSelected();
                //chequeo de existencia de alumno
                if(alumnoActual==null){
                    //se crea alumno y se guarda
                    alumnoActual = new Alumno(dni, apellido, nombre, fechaNacLocalDate, estado);
                    aluData.guardarAlumno(alumnoActual);
                }else {
                    // se toma que el usuario desea modificar datos en caso de que haya alumno  cargado en DB
                    alumnoActual.setDni(dni);
                    alumnoActual.setApellido(apellido);
                    alumnoActual.setNombre(nombre);
                    alumnoActual.setFechaNacimiento(fechaNacLocalDate);
                    aluData.modificarAlumno(alumnoActual);
                }

            }else {
                JOptionPane.showMessageDialog(this, "No puede haber existir campos vacios");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
        }

    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTextField_apellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidoActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jButton_nuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo2ActionPerformed
        // TODO add your handling code here:
        limpiarCamposPantalla();
        alumnoActual=null;

    }//GEN-LAST:event_jButton_nuevo2ActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        // TODO add your handling code here:
        if (alumnoActual!=null) {
            aluData.eliminarAlumno(alumnoActual.getIdAlumno());
            alumnoActual=null;
            limpiarCamposPantalla();
        } else  {
            JOptionPane.showMessageDialog(this, "No hay un alumno seleccionado");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        // TODO add your handling code here:
        try {
            Integer dni = Integer.parseInt(jTextField_dni.getText());
            String nombre = jTextField_nombre.getText();
            String apellido = jTextField_apellido.getText();
            if ( !nombre.isEmpty() && !apellido.isEmpty() ) {
                //extracción de datos
                java.util.Date fechaNacDate = jDateChooser_fechaNaci.getDate();
                //de Date a localdate
                LocalDate fechaNacLocalDate = fechaNacDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                boolean estado = jCheckBox_Activo.isSelected();
                //chequeo de existencia de alumno
                if(alumnoActual==null){
                    //se crea alumno y se guarda
                    alumnoActual = new Alumno(dni, apellido, nombre, fechaNacLocalDate, estado);
                    aluData.guardarAlumno(alumnoActual);
                }else {
                    // se toma que el usuario desea modificar datos en caso de que haya alumno  cargado en DB
                    alumnoActual.setDni(dni);
                    alumnoActual.setApellido(apellido);
                    alumnoActual.setNombre(nombre);
                    alumnoActual.setFechaNacimiento(fechaNacLocalDate);
                    aluData.modificarAlumno(alumnoActual);
                }

            }else {
                JOptionPane.showMessageDialog(this, "No puede haber existir campos vacios");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
        }

    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        //se llama al metodo simplemente
        dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_nuevo2;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JCheckBox jCheckBox_Activo;
    private com.toedter.calendar.JDateChooser jDateChooser_fechaNaci;
    private javax.swing.JLabel jLabel_AlumnoTItulo;
    private javax.swing.JLabel jLabel_Estado;
    private javax.swing.JLabel jLabel_apellido;
    private javax.swing.JLabel jLabel_dni;
    private javax.swing.JLabel jLabel_fechaNac;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JTextField jTextField_apellido;
    private javax.swing.JTextField jTextField_dni;
    private javax.swing.JTextField jTextField_nombre;
    // End of variables declaration//GEN-END:variables

    private void limpiarCamposPantalla() {
        jTextField_apellido.setText("");
        jTextField_dni.setText("");
        jTextField_nombre.setText("");
        jCheckBox_Activo.setSelected(true);
        jDateChooser_fechaNaci.setDate(null);
    }
}
