/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package transversal_vista;

import java.util.List;
//import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import transversal_accesoDeDatos.InscripcionData;
import transversal_accesoDeDatos.MateriaData;
import transversal_entidades.Alumno;
//import transversal_entidades.Inscripcion;
import transversal_entidades.Materia;


public class FormularioConsultaAlumnoPorMateria extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    
    private List<Alumno> listaAlumno =null;
  //  private List<Materia> listaMateria;
  //  private List<MateriaData> listaMateriaData;
   // private List<Inscripcion> listaInscripcion;
    
    private InscripcionData inscData;
    private MateriaData matData;
    private Alumno aluData;
    
    public FormularioConsultaAlumnoPorMateria() {
        initComponents();
        modeloTabla = new DefaultTableModel(); 
        
        inscData = new InscripcionData();
        matData = new MateriaData();
        armarCabecera();
        
        cargarMaterias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_AlumnoTItulo = new javax.swing.JLabel();
        jcomboBoxMateria = new javax.swing.JComboBox<>();
        jLabel1_materia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_listadoMateriaAlumnos = new javax.swing.JTable();
        jButton_salir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Consulta de alumnos por materia");

        jLabel_AlumnoTItulo.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel_AlumnoTItulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/students.png"))); // NOI18N
        jLabel_AlumnoTItulo.setText(" Listado de alumnos por materia");

        jcomboBoxMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBoxMateriaActionPerformed(evt);
            }
        });

        jLabel1_materia.setText("Seleccione una materia:");

        jTable1_listadoMateriaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_listadoMateriaAlumnos);

        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transversal_accesoDeDatos/recursos/salir.png"))); // NOI18N
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_salir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1_materia)
                        .addGap(32, 32, 32)
                        .addComponent(jcomboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel_AlumnoTItulo, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel_AlumnoTItulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1_materia)
                    .addComponent(jcomboBoxMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        //se llama al metodo simplemente
        dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jcomboBoxMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBoxMateriaActionPerformed
        // TODO add your handling code here:
        borrarFilas();
        Materia materiaElegida = (Materia) jcomboBoxMateria.getSelectedItem();

        // Obtengo la lista de alumnos directamente
        listaAlumno = inscData.alumnosPorMateria(materiaElegida.getIdMateria());

        if (!listaAlumno.isEmpty()) {
            for (Alumno auxAlumno : listaAlumno) {
                modeloTabla.addRow(new Object[]{
                    auxAlumno.getIdAlumno(),
                    auxAlumno.getDni(),
                    auxAlumno.getApellido(),
                    auxAlumno.getNombre()
                });
            } 
        }
    }//GEN-LAST:event_jcomboBoxMateriaActionPerformed
    
    private void cargarMaterias() {
        for (Materia aux : matData.listarMateria() ) {
            jcomboBoxMateria.addItem(aux);
        }
    }

    private void borrarFilas() {
        int indice = modeloTabla.getRowCount();
        for (int i = indice; i > 0; i--) {
            modeloTabla.removeRow(0);
        }
    }

    private void armarCabecera () {
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombre");
        jTable1_listadoMateriaAlumnos.setModel(modeloTabla);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel1_materia;
    private javax.swing.JLabel jLabel_AlumnoTItulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_listadoMateriaAlumnos;
    private javax.swing.JComboBox<Materia> jcomboBoxMateria;
    // End of variables declaration//GEN-END:variables

    
}
